name = "profile"
main = "server.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"

# Direct Cloudflare Workers to serve built static assets from ./dist
[assets]
directory = "./dist"
